language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t hideo/react-course-app-dev -f Dockerfile.dev . 
script:
  - docker run -e CI=true hideo/react-course-app-dev npm rum test
  